### ISSUE TITLE
Apart[] doesn't work with repeated factors in the denominator

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mirchaemanuel/symja#9]
```
Input: 
  Apart[(10*x^2-63*x+29)/(x^3-11*x^2+40*x-48)]

The third case: "A repeated first-degree factor in the denominator"
in the Wikipedia Example:
 http://en.wikipedia.org/wiki/Partial_fraction
doesn't work

Output from JAS:
Exception in thread "main" java.lang.RuntimeException: not solvable, r
= -63 , c = 10 x^2 - 63 x + 29 , g = x - 4
       at
edu.jas.ufd.GreatestCommonDivisorAbstract.baseGcdDiophant(GreatestCommonDivisorA
bstract.java:701)
       at
edu.jas.ufd.GreatestCommonDivisorAbstract.basePartialFraction(GreatestCommonDivi
sorAbstract.java:847)
       at edu.jas.integrate.Examples.example4(Examples.java:317)
       at edu.jas.integrate.Examples.main(Examples.java:50)


```

Original issue reported on code.google.com by `axelclk@gmail.com` on 22 Nov 2009 at 9:01

**Comment by GoogleCodeExporter** [comment]
```
Solved with:
http://code.google.com/p/symja/source/detail?r=282
```

Original comment by `axelclk@gmail.com` on 23 Nov 2009 at 9:25
- Changed state: **Fixed**
